//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.17 at 01:57:45 PM MSK 
//


package ru.splat.kateandrewserviceprojectgenerated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eventEntryTCP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eventEntryTCP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lineups" type="{}lineupList" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="matchid" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="event_number" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="event_code_id" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="event_code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minute" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="tickerstate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tickerstateid" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="score_home" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="score_away" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="clears_event" type="{}clear" />
 *       &lt;attribute name="related_events" type="{}clear" />
 *       &lt;attribute name="related_event_codes" type="{}clear" />
 *       &lt;attribute name="zone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="team_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="player_in_num" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="player_out_num" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="player_in_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="player_out_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="player_in_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="player_out_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="event_reason" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="event_reason_id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="player_num" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="player_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="player_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="stoppage_time" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="statistics" type="{}statistics" />
 *       &lt;attribute name="value_event_data" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="score" type="{}statistics" />
 *       &lt;attribute name="currentPlaytime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="clockRunning" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="correctPlaytime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="attendance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="attendance_id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="pitch_condition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pitch_condition_id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="weather_condition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="weather_condition_id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="message_id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="event_state_id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="event_state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="imported_game_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventEntryTCP", propOrder = {
    "lineups"
})
public class EventEntryTCP {

    protected List<LineupList> lineups;
    @XmlAttribute(name = "matchid", required = true)
    protected int matchid;
    @XmlAttribute(name = "event_number")
    protected Short eventNumber;
    @XmlAttribute(name = "event_code_id", required = true)
    protected short eventCodeId;
    @XmlAttribute(name = "timestamp", required = true)
    protected long timestamp;
    @XmlAttribute(name = "event_code")
    protected String eventCode;
    @XmlAttribute(name = "minute")
    protected Short minute;
    @XmlAttribute(name = "tickerstate")
    protected String tickerstate;
    @XmlAttribute(name = "tickerstateid")
    protected Short tickerstateid;
    @XmlAttribute(name = "score_home")
    protected Short scoreHome;
    @XmlAttribute(name = "score_away")
    protected Short scoreAway;
    @XmlAttribute(name = "clears_event")
    protected List<Short> clearsEvent;
    @XmlAttribute(name = "related_events")
    protected List<Short> relatedEvents;
    @XmlAttribute(name = "related_event_codes")
    protected List<Short> relatedEventCodes;
    @XmlAttribute(name = "zone")
    protected String zone;
    @XmlAttribute(name = "team_id")
    protected Integer teamId;
    @XmlAttribute(name = "player_in_num")
    protected Short playerInNum;
    @XmlAttribute(name = "player_out_num")
    protected Short playerOutNum;
    @XmlAttribute(name = "player_in_id")
    protected Integer playerInId;
    @XmlAttribute(name = "player_out_id")
    protected Integer playerOutId;
    @XmlAttribute(name = "player_in_name")
    protected String playerInName;
    @XmlAttribute(name = "player_out_name")
    protected String playerOutName;
    @XmlAttribute(name = "event_reason")
    protected String eventReason;
    @XmlAttribute(name = "event_reason_id")
    protected Short eventReasonId;
    @XmlAttribute(name = "player_num")
    protected Short playerNum;
    @XmlAttribute(name = "player_id")
    protected Integer playerId;
    @XmlAttribute(name = "player_name")
    protected String playerName;
    @XmlAttribute(name = "stoppage_time")
    protected Short stoppageTime;
    @XmlAttribute(name = "statistics")
    protected List<String> statistics;
    @XmlAttribute(name = "value_event_data")
    protected String valueEventData;
    @XmlAttribute(name = "score")
    protected List<String> score;
    @XmlAttribute(name = "currentPlaytime")
    protected Long currentPlaytime;
    @XmlAttribute(name = "clockRunning")
    protected Boolean clockRunning;
    @XmlAttribute(name = "correctPlaytime")
    protected Long correctPlaytime;
    @XmlAttribute(name = "attendance")
    protected String attendance;
    @XmlAttribute(name = "attendance_id")
    protected Short attendanceId;
    @XmlAttribute(name = "pitch_condition")
    protected String pitchCondition;
    @XmlAttribute(name = "pitch_condition_id")
    protected Short pitchConditionId;
    @XmlAttribute(name = "weather_condition")
    protected String weatherCondition;
    @XmlAttribute(name = "weather_condition_id")
    protected Short weatherConditionId;
    @XmlAttribute(name = "message")
    protected String message;
    @XmlAttribute(name = "message_id")
    protected Short messageId;
    @XmlAttribute(name = "event_state_id")
    protected Short eventStateId;
    @XmlAttribute(name = "event_state")
    protected String eventState;
    @XmlAttribute(name = "imported_game_id")
    protected String importedGameId;

    /**
     * Gets the value of the lineups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineupList }
     * 
     * 
     */
    public List<LineupList> getLineups() {
        if (lineups == null) {
            lineups = new ArrayList<LineupList>();
        }
        return this.lineups;
    }

    /**
     * Gets the value of the matchid property.
     * 
     */
    public int getMatchid() {
        return matchid;
    }

    /**
     * Sets the value of the matchid property.
     * 
     */
    public void setMatchid(int value) {
        this.matchid = value;
    }

    /**
     * Gets the value of the eventNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getEventNumber() {
        return eventNumber;
    }

    /**
     * Sets the value of the eventNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setEventNumber(Short value) {
        this.eventNumber = value;
    }

    /**
     * Gets the value of the eventCodeId property.
     * 
     */
    public short getEventCodeId() {
        return eventCodeId;
    }

    /**
     * Sets the value of the eventCodeId property.
     * 
     */
    public void setEventCodeId(short value) {
        this.eventCodeId = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     */
    public void setTimestamp(long value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the eventCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventCode() {
        return eventCode;
    }

    /**
     * Sets the value of the eventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventCode(String value) {
        this.eventCode = value;
    }

    /**
     * Gets the value of the minute property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getMinute() {
        return minute;
    }

    /**
     * Sets the value of the minute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setMinute(Short value) {
        this.minute = value;
    }

    /**
     * Gets the value of the tickerstate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTickerstate() {
        return tickerstate;
    }

    /**
     * Sets the value of the tickerstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTickerstate(String value) {
        this.tickerstate = value;
    }

    /**
     * Gets the value of the tickerstateid property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getTickerstateid() {
        return tickerstateid;
    }

    /**
     * Sets the value of the tickerstateid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setTickerstateid(Short value) {
        this.tickerstateid = value;
    }

    /**
     * Gets the value of the scoreHome property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getScoreHome() {
        return scoreHome;
    }

    /**
     * Sets the value of the scoreHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setScoreHome(Short value) {
        this.scoreHome = value;
    }

    /**
     * Gets the value of the scoreAway property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getScoreAway() {
        return scoreAway;
    }

    /**
     * Sets the value of the scoreAway property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setScoreAway(Short value) {
        this.scoreAway = value;
    }

    /**
     * Gets the value of the clearsEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clearsEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClearsEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getClearsEvent() {
        if (clearsEvent == null) {
            clearsEvent = new ArrayList<Short>();
        }
        return this.clearsEvent;
    }

    /**
     * Gets the value of the relatedEvents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedEvents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedEvents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getRelatedEvents() {
        if (relatedEvents == null) {
            relatedEvents = new ArrayList<Short>();
        }
        return this.relatedEvents;
    }

    /**
     * Gets the value of the relatedEventCodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedEventCodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedEventCodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getRelatedEventCodes() {
        if (relatedEventCodes == null) {
            relatedEventCodes = new ArrayList<Short>();
        }
        return this.relatedEventCodes;
    }

    /**
     * Gets the value of the zone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZone() {
        return zone;
    }

    /**
     * Sets the value of the zone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZone(String value) {
        this.zone = value;
    }

    /**
     * Gets the value of the teamId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * Sets the value of the teamId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTeamId(Integer value) {
        this.teamId = value;
    }

    /**
     * Gets the value of the playerInNum property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPlayerInNum() {
        return playerInNum;
    }

    /**
     * Sets the value of the playerInNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPlayerInNum(Short value) {
        this.playerInNum = value;
    }

    /**
     * Gets the value of the playerOutNum property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPlayerOutNum() {
        return playerOutNum;
    }

    /**
     * Sets the value of the playerOutNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPlayerOutNum(Short value) {
        this.playerOutNum = value;
    }

    /**
     * Gets the value of the playerInId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPlayerInId() {
        return playerInId;
    }

    /**
     * Sets the value of the playerInId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPlayerInId(Integer value) {
        this.playerInId = value;
    }

    /**
     * Gets the value of the playerOutId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPlayerOutId() {
        return playerOutId;
    }

    /**
     * Sets the value of the playerOutId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPlayerOutId(Integer value) {
        this.playerOutId = value;
    }

    /**
     * Gets the value of the playerInName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayerInName() {
        return playerInName;
    }

    /**
     * Sets the value of the playerInName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayerInName(String value) {
        this.playerInName = value;
    }

    /**
     * Gets the value of the playerOutName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayerOutName() {
        return playerOutName;
    }

    /**
     * Sets the value of the playerOutName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayerOutName(String value) {
        this.playerOutName = value;
    }

    /**
     * Gets the value of the eventReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventReason() {
        return eventReason;
    }

    /**
     * Sets the value of the eventReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventReason(String value) {
        this.eventReason = value;
    }

    /**
     * Gets the value of the eventReasonId property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getEventReasonId() {
        return eventReasonId;
    }

    /**
     * Sets the value of the eventReasonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setEventReasonId(Short value) {
        this.eventReasonId = value;
    }

    /**
     * Gets the value of the playerNum property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPlayerNum() {
        return playerNum;
    }

    /**
     * Sets the value of the playerNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPlayerNum(Short value) {
        this.playerNum = value;
    }

    /**
     * Gets the value of the playerId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * Sets the value of the playerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPlayerId(Integer value) {
        this.playerId = value;
    }

    /**
     * Gets the value of the playerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * Sets the value of the playerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayerName(String value) {
        this.playerName = value;
    }

    /**
     * Gets the value of the stoppageTime property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getStoppageTime() {
        return stoppageTime;
    }

    /**
     * Sets the value of the stoppageTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setStoppageTime(Short value) {
        this.stoppageTime = value;
    }

    /**
     * Gets the value of the statistics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statistics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatistics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getStatistics() {
        if (statistics == null) {
            statistics = new ArrayList<String>();
        }
        return this.statistics;
    }

    /**
     * Gets the value of the valueEventData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueEventData() {
        return valueEventData;
    }

    /**
     * Sets the value of the valueEventData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueEventData(String value) {
        this.valueEventData = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the score property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getScore() {
        if (score == null) {
            score = new ArrayList<String>();
        }
        return this.score;
    }

    /**
     * Gets the value of the currentPlaytime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCurrentPlaytime() {
        return currentPlaytime;
    }

    /**
     * Sets the value of the currentPlaytime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCurrentPlaytime(Long value) {
        this.currentPlaytime = value;
    }

    /**
     * Gets the value of the clockRunning property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClockRunning() {
        return clockRunning;
    }

    /**
     * Sets the value of the clockRunning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClockRunning(Boolean value) {
        this.clockRunning = value;
    }

    /**
     * Gets the value of the correctPlaytime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCorrectPlaytime() {
        return correctPlaytime;
    }

    /**
     * Sets the value of the correctPlaytime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCorrectPlaytime(Long value) {
        this.correctPlaytime = value;
    }

    /**
     * Gets the value of the attendance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttendance() {
        return attendance;
    }

    /**
     * Sets the value of the attendance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttendance(String value) {
        this.attendance = value;
    }

    /**
     * Gets the value of the attendanceId property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getAttendanceId() {
        return attendanceId;
    }

    /**
     * Sets the value of the attendanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setAttendanceId(Short value) {
        this.attendanceId = value;
    }

    /**
     * Gets the value of the pitchCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPitchCondition() {
        return pitchCondition;
    }

    /**
     * Sets the value of the pitchCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPitchCondition(String value) {
        this.pitchCondition = value;
    }

    /**
     * Gets the value of the pitchConditionId property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPitchConditionId() {
        return pitchConditionId;
    }

    /**
     * Sets the value of the pitchConditionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPitchConditionId(Short value) {
        this.pitchConditionId = value;
    }

    /**
     * Gets the value of the weatherCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeatherCondition() {
        return weatherCondition;
    }

    /**
     * Sets the value of the weatherCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeatherCondition(String value) {
        this.weatherCondition = value;
    }

    /**
     * Gets the value of the weatherConditionId property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getWeatherConditionId() {
        return weatherConditionId;
    }

    /**
     * Sets the value of the weatherConditionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setWeatherConditionId(Short value) {
        this.weatherConditionId = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setMessageId(Short value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the eventStateId property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getEventStateId() {
        return eventStateId;
    }

    /**
     * Sets the value of the eventStateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setEventStateId(Short value) {
        this.eventStateId = value;
    }

    /**
     * Gets the value of the eventState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventState() {
        return eventState;
    }

    /**
     * Sets the value of the eventState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventState(String value) {
        this.eventState = value;
    }

    /**
     * Gets the value of the importedGameId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportedGameId() {
        return importedGameId;
    }

    /**
     * Sets the value of the importedGameId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportedGameId(String value) {
        this.importedGameId = value;
    }

}
